# -*- coding: utf-8 -*-
"""II parte.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-i2gB9upI9WQWwMhCU3WZpY7SdKoguK
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

url=("https://raw.githubusercontent.com/moisesabregom/parcial2/main/Elementos.csv")
df=pd.read_csv(url)
df

x1=df["PE"]
x2=df["PF"]
y=df["NA"]
plt.plot(y,x1,color="green")
plt.plot(y,x2,color="blue")
plt.xlabel("Númeor átomico")
plt.ylabel("Temperatura (K)")
plt.title("Punto De Ebullición y Fusión vs Número Átomico")
plt.show()