# -*- coding: utf-8 -*-
"""IVparte.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bb9vi2Xx5NIe_VjrlS3I7dtDTt2liLPr
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(0,10)

y=3.0*2*np.exp(-1.5*x)*np.sin(2*x)

plt.plot(x,y)
plt.show()